[Variables]
FontName=Segoe UI
CardRadius=0
ConferenceName=ICNP 2026
ConferenceInfo=October 5-8, 2026 Tempe, Arizona, USA
ConferenceSite = https://icnp26.cs.ucr.edu/
ConferenceDesc=International Conference on Network Protocols
ConferenceNote=Abstract on May 16, Full Paper on May 22
Deadline=2026-05-22 23:59:59
CardWidth=344
CardHeight=93
CardRadius=6

CardBg=245,245,245,255
CardBorder=210,210,210,255
TitleColor=40,70,110,255
CountdownColor=110,110,110,255
SubColor=90,90,90,255
TextColor=50,50,50,255
NoteColor=40,110,230,255

Title=ICNP 2026
DateLocation=October 5-8, 2026 Tempe, Arizona, USA
Description=IEEE International Conference on Network Protocols
Note=NOTE: Abstract deadline on May 16, 2026.

Deadline=2026-05-16 23:59:59